version: 0.2

phases:
  build:
    commands:
      # Print the branch name
      #- echo "Branch Name: ${CODEBUILD_SOURCE_VERSION#refs/heads/}"
      # Checkout the source code
      - git clone https://github.com/nandireddy12321/cms-angular.git
      
      # Build Docker image
      - docker build -t cmswebapi .
      # Print Docker image name with tag of build number
      #- echo "Docker Image Name: cmswebapi"

  post_build:
    commands:
      # Log in to AWS CodeArtifact using AWS CLI
      - aws codeartifact login --tool npm --repository spotify --domain lokiiii
      # Print whether login succeeded or not
      - if [ $? -eq 0 ]; then echo "Login to CodeArtifact succeeded"; else echo "Login to CodeArtifact failed"; fi
      # Push Docker image to AWS CodeArtifact
      - >
       # docker tag spotify \
          891377224117.d.codeartifact.ap-south-1.amazonaws.com/lokiiii/spotify:$CODEBUILD_BUILD_NUMBER
      - docker push cmswebapi
