apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-angular
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cms-angular
  template:
    metadata:
      labels:
        app: cms-angular
    spec:
      containers:
      - name: my-app
        image: cmsangular:10
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
