apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webappingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /cms
            backend:
              service:
                name: cmsangular
                port:
                  number: 8081  
          - pathType: Prefix
            path: /spotify
            backend:
              service:
                name: spotify
                port:
                  number: 8083  
