apiVersion: v1
kind: Service
metadata:
  name: cmsangular-servicelb
  labels: 
    app: cms-angular
spec:
  type: LoadBalancer
  selector:
    app: cms-angular
  ports:
    - protocol: TCP
      port: 80
